""" Add language column to projects

Revision ID: 219963bb18dc
Revises: 4f685c062cff
Create Date: 2015-09-21 18:06:53.922781

"""

# revision identifiers, used by Alembic.
revision = '219963bb18dc'
down_revision = '4f685c062cff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('languages', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'languages')
    ### end Alembic commands ###
