""" Add commit status

Revision ID: 29ef29bfbe43
Revises: 6cee2da7d1f
Create Date: 2016-01-31 22:49:31.651206

"""

# revision identifiers, used by Alembic.
revision = '29ef29bfbe43'
down_revision = '6cee2da7d1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('commit_status', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'commit_status')
    ### end Alembic commands ###
